services:
  redis:
    image: redis
    ports:
      - "6379"
    restart: always

  aipartner:
    image: hwjdk:21
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./jars:/jars
      - ./db:/db
    command: ["-Dfile.encoding=utf-8", "-Xmx1024m", "-jar", "/jars/aipartner-0.0.1-SNAPSHOT.jar"]
