openai:
  base-url: https://api.deepseek.com
  api-key: sk-27458ffa9db74d6096b2462dcc4b0b62
  #base-url: https://dashscope.aliyuncs.com/compatible-mode
  #api-key: sk-3d5122d342aa47d68ca9ed6aafde1d37

anythingllm:
  base-url: http://www.liuhongtian.com:23001
  api-key: 9ZCGHF0-WR6MA0B-HQ8Q2S4-HQ39KQK
  #mbp api-key: AW6F4YM-9ZXMMS0-PM025QX-W1CXSZ3
  #pc api-key: SFVWXJ5-F0XM63A-KCVS6VY-6PZXX9M
  #aliyun api-key: 9ZCGHF0-WR6MA0B-HQ8Q2S4-HQ39KQK

cors:
  allowed-origin-patterns: http://localhost,https://localhost,http://localhost:*,https://localhost:*,http://svr39.bjhwsj.com,http://www.liuhongtian.com:*,http://mmliuhongtian.xyz:*
spring:
  data:
    redis:
      host: redis
      port: 6379
      # password: # 如果有密码，请取消注释并设置密码
      database: 0
      timeout: 10000

  datasource:
    # url最容易出错，如果使用相对于项目的相对地址，那么填入 jdbc:sqlite::resource:sqlit数据库所在位置
    # 注：
    # :resource: 指向项目的 resources 路径（resource前后两个 `:` 不能省略）
    #url: jdbc:sqlite::resource:db/access_log.sqlite
    url: jdbc:sqlite:db/access_log.sqlite
    driver-class-name: org.sqlite.JDBC
    # username: 选用 sqlite 数据库不需要配置此项
    # password: 选用 sqlite 数据库不需要配置此项
  sql:
    init:
      # DDL建表语句
      schema-locations: classpath:db/schema.sql
      # DML添加数据
      #data-locations: classpath:db/data.sql
      mode: always
      continue-on-error: true
